Repository spf13/viper, pull requests merged in 2023-11, with the labels that each got.

#1693 refactor: drop fsonitfy wrapper
  viper.go
  watch.go
  watch_unsupported.go
Labels: release-note/misc

#1694 chore: update dependencies
  go.mod
  go.sum
Labels: area/dependencies

#1687 Note Get* behavior on parse failure
  README.md
Labels: area/documentation, release-note/misc

#1657 fix: godot lint issues
  .golangci.yaml
  file.go
  flags.go
  internal/encoding/dotenv/codec_test.go
  internal/encoding/dotenv/map_utils.go
  internal/encoding/hcl/codec_test.go
  internal/encoding/ini/codec_test.go
  internal/encoding/ini/map_utils.go
  internal/encoding/javaproperties/codec_test.go
  internal/encoding/javaproperties/map_utils.go
  internal/encoding/json/codec_test.go
  internal/encoding/toml/codec_test.go
  internal/encoding/yaml/codec_test.go
  overrides_test.go
  util.go
  viper.go
  viper_test.go
Labels: release-note/misc
