Repository spf13/viper, pull requests merged in 2023-01, with the labels that each got.

#1485 Provide a link to explain what a 12-factor app is
  README.md
Labels: release-note/ignore

#1494 Drop support for Go 1.16
  .github/workflows/ci.yaml
  Makefile
Labels: release-note/breaking-change

#1464 feat: add multiple endpoints support for remote
  remote/remote.go
Labels: release-note/new-feature

#1467 Add DocBlock to WatchConfig
  viper.go
Labels: release-note/enhancement
