Repository spf13/viper, pull requests merged in 2023-06, with the labels that each got.

#1561 fix the `Restore cache failed` warning of the ci.yaml github actions job
  .github/workflows/ci.yaml
Labels: release-note/ignore

#1565 feat: add func GetEnvPrefix
  viper.go
Labels: kind/enhancement

#1574 feat: drop support for Go 1.17
  .github/workflows/ci.yaml
  README.md
  go.mod
  go.sum
Labels: release-note/breaking-change
