Repository spf13/viper, pull requests merged in 2023-09, with the labels that each got.

#1609 docs: fix typos in comments
  README.md
  flags.go
  internal/encoding/dotenv/map_utils.go
  internal/encoding/ini/map_utils.go
  internal/encoding/javaproperties/map_utils.go
  logger.go
  viper_test.go
Labels: release-note/misc

#1610 test: remove not needed testutil.Setenv
  internal/testutil/env_go1_16.go
  internal/testutil/env_go1_17.go
  util_test.go
  viper_test.go
Labels: kind/enhancement

#1621 chore(deps): update crypt
  go.mod
  go.sum
Labels: area/dependencies

#1590 Add NATS support
  README.md
  remote/remote.go
  viper.go
Labels: kind/enhancement, release-note/new-feature

#1626 Bump minimum Go version to 1.19
  .github/workflows/ci.yaml
  README.md
Labels: release-note/dependency-update

#1631 Remove usages of deprecated io/ioutil; simplify viper tests
  viper_test.go
Labels: release-note/misc

#1630 chore: remove deprecated build tags
  viper_go1_15.go
  viper_go1_16.go
  watch.go
  watch_unsupported.go
Labels: release-note/misc
