Repository spf13/viper, pull requests merged in 2023-10, with the labels that each got.

#1646 refactor: replace 'interface{}' with 'any'
  README.md
  internal/encoding/decoder.go
  internal/encoding/decoder_test.go
  internal/encoding/dotenv/codec.go
  internal/encoding/dotenv/codec_test.go
  internal/encoding/dotenv/map_utils.go
  internal/encoding/encoder.go
  internal/encoding/encoder_test.go
  internal/encoding/hcl/codec.go
  internal/encoding/hcl/codec_test.go
  internal/encoding/ini/codec.go
  internal/encoding/ini/codec_test.go
  internal/encoding/ini/map_utils.go
  internal/encoding/javaproperties/codec.go
  internal/encoding/javaproperties/codec_test.go
  internal/encoding/javaproperties/map_utils.go
  internal/encoding/json/codec.go
  internal/encoding/json/codec_test.go
  internal/encoding/toml/codec.go
  internal/encoding/toml/codec_test.go
  internal/encoding/yaml/codec.go
  internal/encoding/yaml/codec_test.go
  logger.go
  overrides_test.go
  util.go
  util_test.go
  viper.go
  viper_test.go
Labels: release-note/misc

#1644 test: refactor asserts
  flags_test.go
  overrides_test.go
  viper_test.go
Labels: release-note/misc

#1652 chore(deps): update crypt
  go.mod
  go.sum
Labels: area/dependencies

#1650 refactor: make use of `strings.Cut`
  viper.go
Labels: kind/enhancement

#1642 chore: rename files according to enabled build tags
  file.go
  file_finder.go
Labels: kind/enhancement

#1656 test: replace ifs with asserts to simplify tests
  flags_test.go
  internal/encoding/decoder_test.go
  internal/encoding/dotenv/codec_test.go
  internal/encoding/encoder_test.go
  internal/encoding/hcl/codec_test.go
  internal/encoding/ini/codec_test.go
  internal/encoding/javaproperties/codec_test.go
  internal/encoding/json/codec_test.go
  internal/encoding/toml/codec_test.go
  internal/encoding/yaml/codec_test.go
  util_test.go
  viper_test.go
Labels: release-note/enhancement
