Repository spf13/viper, pull requests merged in 2024-06, with the labels that each got.

#1834 chore: update crypt
  go.mod
  go.sum
Labels: area/dependencies

#1847 refactor: move remote code to separate file
  remote.go
  viper.go
Labels: release-note/misc

#1854 Add experimental flag for bind struct
  experimental.go
  viper.go
  viper_test.go
Labels: kind/enhancement

#1861 Revert to go-difflib and go-spew releases
  go.mod
  go.sum
Labels: area/dependencies

#1866 chore: update crypt
  remote/go.mod
  remote/go.sum
Labels: area/dependencies

#1871 fix: do not allow setting dependencies to nil values
  encoding.go
  finder.go
  viper.go
Labels: kind/bug

#1872 Add decoder hook option
  viper.go
  viper_test.go
Labels: kind/enhancement
