Repository spf13/viper, pull requests merged in 2024-07, with the labels that each got.

#1884 chore(deps): update crypt
  remote/go.mod
  remote/go.sum
Labels: area/dependencies

#1887 feat: copy keydelim from parent chart in viper.Sub()
  viper.go
  viper_test.go
Labels: kind/bug

#1888 chore: update dependencies
  remote/go.mod
  remote/go.sum
Labels: area/dependencies

#1889 refactor: cleanup unused encoding code
  internal/encoding/decoder.go
  internal/encoding/decoder_test.go
  internal/encoding/encoder.go
  internal/encoding/encoder_test.go
  internal/encoding/error.go
Labels: release-note/misc
