Repository spf13/viper, pull requests merged in 2025-03, with the labels that each got.

#1992 docs: add update instructions for 1.20
  UPDATES.md
Labels: area/documentation, release-note/misc

#1993 Update dependencies
  README.md
  go.mod
  go.sum
  remote/go.mod
  remote/go.sum
Labels: area/dependencies

#2003 fix(config): get config type from v.configType or config file ext
  viper.go
  viper_test.go
Labels: kind/bug

#2004 Update update guide with `mapstructure` package replacement.
  UPGRADE.md
Labels: area/documentation

#2007 fix: config type check when loading any config
  viper.go
Labels: kind/bug
